dist: xenial
language: python
python:
  - 3.7
  - 3.6
  - 2.7
env:
  - TOX_SKIP_ENV=".*djangomaster.*"
  - TOX_SKIP_ENV=".*django[^m].*"
matrix:
  exclude:
    - python: 2.7
      env: TOX_SKIP_ENV=".*django[^m].*"
  allow_failures:
    - env: TOX_SKIP_ENV=".*django[^m].*"
script: tox
notifications:
  email: false
install:
  - pip install tox tox-venv tox-travis coveralls
after_success:
  - coveralls
